#!/usr/bin/env ruby
# frozen_string_literal: true

require "zoi"

args = File.pipe?($stdin) ? ARGV + ($stdin.gets || '').to_s.chomp.split : ARGV

ENV["THOR_SILENCE_DEPRECATION"] = "true"

Zoi::CLI.start(args)
